apiVersion: batch/v1
kind: Job
metadata:
  name: master
spec:
  template:
    metadata:
      labels:
        app: master
    spec:
      restartPolicy: OnFailure
      containers:
      - name: photon-master
        image: photon:latest
        ports:
        - containerPort: 80
        securityContext:
          privileged: true
        volumeMounts:
        - name: photon
          mountPath: /root
        - name: sys
          mountPath: /sys
          readOnly: false
        workingDir: /root
        command: ["/bin/bash"]
        args: ["-c","tdnf remove -y toybox && \
                     tdnf install -y build-essential createrepo texinfo wget sudo \
                     findutils python3-pip git && \
                     pip3 install flask requests pyOpenSSL docker==2.3.0 && \
                     chmod 755 /sys && \
                     make packages CONTAINER_BUILD=enable"]
      volumes:
      - name: photon
        persistentVolumeClaim:
          claimName: photon
      - name: builder
        persistentVolumeClaim:
          claimName: builder
      - name: sys
        hostPath:
          path: /sys
  backoffLimit: 10
