apiVersion: v1
kind: PersistentVolume
metadata:
  name: photon
  labels:
    storage-tier: photon
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy:
    Retain
  nfs:
    path: /mnt/photon
    server: 10.197.103.161
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: specs
  labels:
    storage-tier: specs
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy:
    Retain
  nfs:
    path: /mnt/photon/SPECS
    server: 10.197.103.161
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rpms
  labels:
    storage-tier: rpms
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy:
    Retain
  nfs:
    path: /mnt/photon/stage/RPMS
    server: 10.197.103.161
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: publishrpms
  labels:
    storage-tier: publishrpms
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy:
    Retain
  nfs:
    path: /mnt/photon/stage/PUBLISHRPMS
    server: 10.197.103.161
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: publishxrpms
  labels:
    storage-tier: publishxrpms
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy:
    Retain
  nfs:
    path: /mnt/photon/stage/PUBLISHXRPMS
    server: 10.197.103.161
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs
  labels:
    storage-tier: logs
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy:
    Retain
  nfs:
    path: /mnt/photon/stage/LOGS
    server: 10.197.103.161
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: builder
  labels:
    storage-tier: builder
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy:
    Retain
  nfs:
    path: /mnt/photon/support/package-builder
    server: 10.197.103.161
